language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t borisullmann/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true borisullmann/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  environment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-988037320434"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
