language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t borisullmann/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true borisullmann/docker-react npm run test